config/routes.rb
Modeldemo::Application.routes.draw do
  root 'customers#index'

  resources :customers do
    resources :orders
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base

  validates :name, :city, :address, presence: true
  has_many :orders , :dependent => :destroy
  scope :search, ->(keyword){ where('name LIKE ?', "%#{keyword.downcase}%") if keyword.present? }

end

app/models/order.rb
class Order < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :customer # , :class_name=>"Customer",:foreign_key => "customer_id"
  scope :search, ->(keyword){ where('name LIKE ?', "%#{keyword.downcase}%") if keyword.present? }
 end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def index
    @customers = Customer.search(params[:keyword])
    fresh_when(@customers)
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def edit
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to @customer, notice: 'Customer was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to @customer, notice: 'Customer was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @customer.destroy
    redirect_to customers_url
  end

  private

  def set_customer
    @customer = Customer.find(params[:id])
  end

  def customer_params
    params.required(:customer).permit(:name, :address, :city, :status)
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :get_customer

  def index
    @orders = @customer.orders.search(params[:keyword])
  end

  def show
    @order = @customer.orders.find(params[:id])
  end

  def new
    @order = @customer.orders.build
  end

  def edit
  end

  def create
    @order = @customer.orders.new(order_params)
    if @order.save
       redirect_to [@customer, @order], notice: 'Order was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @order = @customer.orders.find(params[:id])
    if @order.update(order_params)
      redirect_to [@customer, @order], notice: 'Order was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @order = @customer.orders.find(params[:id] )
    @order.destroy
    redirect_to customer_orders_path, notice: 'Order was successfully destroyed.'
  end

  def get_customer
    @customer = Customer.find(params[:customer_id])
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def order_params
    params.required(:order).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
    <% if @customer.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

          <ul>
            <% @customer.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :address %><br>
      <%= f.text_area :address, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :city %><br>
      <%= f.text_field :city, class:'form-control' %>
    </div>
    <div class="form-group">
      <%= f.submit class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer , class: "btn btn-info"%> |
<%= link_to 'Back', customers_path, class: "btn btn-info" %>

app/views/customers/index.html.erb
<h1>Listing All Customersss121122</h1>

<form role="search" style="width: 15em; margin: 0.3em 2em;float: right">
  <div class="input-group">
    <input type='text' class='form-control' value='<%= params[:keyword] %>' name='keyword' placeholder='Keyword' >
    <div class="input-group-btn">
      <button type="submit" class="btn btn-default">
        <span class="glyphicon glyphicon-search"></span>
      </button>
    </div>
  </div>
</form>

<table class='table table-bordered'>

  <thead>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>City</th>
    <th>Show</th>
    <th>Edit</th>
    <th>Destroy</th>
    <th>Create Order</th>
    <th>View Complete Order</th>
  </tr>
  </thead>

  <tbody class='table-striped'>
  <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.address %></td>
        <td><%= customer.city %></td>
        <td><%= link_to 'Show', customer, class: "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_customer_path(customer), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', customer, method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class: "btn btn-danger" %></td>
        <td><%= link_to 'Create order', new_customer_order_path(customer) , class: "btn btn-primary"%></td>
        <td><%= link_to 'Complete Order', customer_orders_path(customer), class: "btn btn-info"  %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Customer', new_customer_path, class: "btn btn-success" %>

app/views/customers/new.html.erb
<p id="notice"><%= notice %></p>

<%= render 'form' %>

<%= link_to 'Back', root_path , class: "btn btn-info"%>

app/views/customers/show.html.erb
<div class="alert alert-danger" style="display: none">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
  <%= notice %>
</div>


<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @customer.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @customer.city %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer), class: "btn btn-info" %> |
<%= link_to 'Back', customers_path ,class: "btn btn-info"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Model demo With Bootstrap</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

<!--<div class='footer'>-->
  <!--<div class='container'>-->
    <!--<div class='row'>-->
      <!--<div class='col-sm-2 col-md-offset-1 col-xs-6'>-->
        <!--<h4>Links</h4>-->
        <!--<ul class="list-unstyled">-->
          <!--<li><a href='/'>Home</a></li>-->
          <!--<li><a href='tickets.html'>Tickets</a></li>-->
          <!--<li><a href='stations.html'>Stations</a></li>-->
        <!--</ul>-->
      <!--</div>-->

      <!--<div class='col-sm-2 col-xs-6'>-->
        <!--<h4>Stay in Touch</h4>-->
        <!--<ul class="list-unstyled">-->
          <!--<li><a href='about.html'>About</a></li>-->
          <!--<li><a href='contact.html'>Contact Us</a></li>-->
          <!--<li><a href='/blog'>Blog</a></li>-->
          <!--<li><a href='http://twitter.com/codeschool'>Twitter</a></li>-->
          <!--<li><a href='http://facebook.com/codeschool'>Facebook</a></li>-->
        <!--</ul>-->
      <!--</div>-->

      <!--<div class='clearfix visible-xs'></div>-->

      <!--<div class='col-sm-4 col-md-3 col-xs-6'>-->
        <!--<h4>Who We Are</h4>-->
        <!--<p><i>Blasting Off With Bootstrap</i> is the fastest way to space. <a href='tickets.html'>Book your ticket today</a>!</p>-->
        <!--<p><a href='about.html'>More About Us</a></p>-->
      <!--</div>-->

      <!--<div class='col-sm-4 col-md-3 col-md-offset-1 col-xs-6'>-->
        <!--<h4>Contact Us</h4>-->
        <!--<ul class="list-unstyled">-->
          <!--<li> <i class='glyphicon glyphicon-globe'></i>Orlando, FL</li>-->
          <!--<li><i class='glyphicon glyphicon-phone'></i>1-555-blast-off</li>-->
          <!--<li><i class='glyphicon glyphicon-envelope'></i><a href='mailto:blastingoff@codeschool.com'>blastingoff@codeschool.com</a></li>-->
        <!--</ul>-->
        <!--<p>Blasting Off With Bootstrap &copy;2015-2016</p>-->
      <!--</div>-->
    <!--</div>-->
  <!--</div>-->
<!--</div>-->
</body>
</html>

app/views/orders/_form.html.erb
<%= form_for([@customer, @order]) do |f| %>
    <% if @order.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>
          <ul>
            <% @order.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>

    <div class="actions">
      <%= f.submit class: "btn btn-success" %><br>
    </div>

<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', customer_order_path(@customer, @order), class: "btn btn-info" %> |
<%= link_to 'Back', customer_orders_path(@customer, @order), class: "btn btn-info" %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>

<form role="search" style="width: 15em; margin: 0.3em 2em;float: right">
  <div class="input-group">
    <input type='text' class='form-control' value='<%= params[:keyword] %>' name='keyword' placeholder='Keyword' >
    <div class="input-group-btn">
      <button type="submit" class="btn btn-default">
        <span class="glyphicon glyphicon-search"></span>
      </button>
    </div>
  </div>
</form>

<table class='table table-bordered'>
  <thead>
  <tr>
    <th>Order Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody class='table-striped'>
  <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <!--Remember the brackets is an array of the nested records, which is then "processed"
        by Rails to compute a path for all the given nested records (according to your routes).
        In this case the first element of the array is a Project, second a Thread and third an Attachment.
        Rails "guess" that an Attachment belongs to a Thread which belongs to a Project,
        computing a path with these nested records: project, then thread, then attachment,
        which leads to the helper : project_thread_attachment_path-->
        <td><%= link_to 'Show', customer_order_path(@customer ,order), class: "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_customer_order_path(@customer ,order), class: "btn btn-warning"  %></td>
        <td><%= link_to 'Destroy', [@customer, order], method: :delete,
                        data: { confirm: 'Are you sure?' },
                        class: "btn btn-danger" %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_customer_order_path(@customer), class: "btn btn-info" %>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', customer_orders_path, class: "btn btn-info" %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %>
</p>
<p>
  <strong>Name:</strong>
  <%= @order.name %>
</p>

<%= link_to 'Edit', edit_customer_order_path(@customer, @order) %>
<%= link_to 'Back', customer_orders_path, class: "btn btn-info" %>